name: Build Main Binary And Release

on:
  workflow_dispatch: # 允许手动触发工作流
    inputs:
      tag:
        description: 'Image tag'
        required: true
        default: 'latest'

jobs:
  build-binary:
    uses: czlizy/bili-sync/.github/workflows/build-binary.yaml@main
  github-release:
    name: Create GitHub Release
    needs: build-binary
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: bili-sync-rs*
          tag_name: ${{ github.ref_name }}
          draft: true
  docker-release:
    name: Create Docker Image
    needs: build-binary
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: czlizy/bili-sync-rs
          tags: |
            type=raw,value=latest
            type=raw,value=${{ github.ref_name }}
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/amd64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
      - name: Upload Docker Image as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bili-sync-rs-amd64-image
          path: ./docker-images/*.tar
